// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9PcdC2gBVEaGgIlfRNehM82HuaCcd1ls',
    appId: '1:222788676874:android:5bd0dae09af0000ed75ef3',
    messagingSenderId: '222788676874',
    projectId: 'projects2022-cf398',
    databaseURL: 'https://projects2022-cf398-default-rtdb.firebaseio.com',
    storageBucket: 'projects2022-cf398.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCe4tVN70Aj_IRjdPcxv7PpWm5HU7tb58',
    appId: '1:222788676874:ios:b51cd4cb982ffa45d75ef3',
    messagingSenderId: '222788676874',
    projectId: 'projects2022-cf398',
    databaseURL: 'https://projects2022-cf398-default-rtdb.firebaseio.com',
    storageBucket: 'projects2022-cf398.appspot.com',
    androidClientId: '222788676874-0goeqh9v3j8roc9l3j2dakcvuh6s3la5.apps.googleusercontent.com',
    iosBundleId: 'com.moshtask.app',
  );


}
